name: Build latest images automatically

on:
    push:
        branches: ["master", "main"]
    schedule:
        - cron: "0 0 * * *"
jobs:
    deploy:
        strategy:
            fail-fast: false

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            -
                name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: wh1isper
                    password: ${{ secrets.PAT }}
            - name: Build and push release
              id: docker_build_release
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64/v8
                  file: ./Dockerfile
                  push: true
                  tags: wh1isper/aws-cli-pypi:latest
            - name: Build and push release
              id: ghcr_docker_build_release
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64/v8
                  file: ./Dockerfile
                  push: true
                  tags: ghcr.io/wh1isper/aws-cli-pypi:latest
